# Form implementation generated from reading ui file '.\bulk_update_one.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(480, 171)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 40, 401, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.text_filepath = QtWidgets.QLineEdit(self.layoutWidget)
        self.text_filepath.setObjectName("text_filepath")
        self.horizontalLayout_2.addWidget(self.text_filepath)
        self.btn_choose_file = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_choose_file.setMaximumSize(QtCore.QSize(25, 24))
        self.btn_choose_file.setObjectName("btn_choose_file")
        self.horizontalLayout_2.addWidget(self.btn_choose_file)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 20, 61, 16))
        self.label.setObjectName("label")
        self.btn_update = QtWidgets.QPushButton(Form)
        self.btn_update.setGeometry(QtCore.QRect(270, 80, 75, 26))
        self.btn_update.setMaximumSize(QtCore.QSize(16777215, 28))
        self.btn_update.setObjectName("btn_update")
        self.btn_close = QtWidgets.QPushButton(Form)
        self.btn_close.setGeometry(QtCore.QRect(360, 80, 75, 26))
        self.btn_close.setMaximumSize(QtCore.QSize(16777215, 28))
        self.btn_close.setObjectName("btn_close")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(0, 120, 481, 16))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 140, 341, 16))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_choose_file.setText(_translate("Form", "..."))
        self.label.setText(_translate("Form", "Choose file:"))
        self.btn_update.setText(_translate("Form", "Update"))
        self.btn_close.setText(_translate("Form", "Close"))
        self.label_2.setText(_translate("Form", "Column names: article, stitching, printing  (article format: 0000-BK-G)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
