# Form implementation generated from reading ui file 'ui\menu_app_logs.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AppLogs(object):
    def setupUi(self, AppLogs):
        AppLogs.setObjectName("AppLogs")
        AppLogs.resize(580, 584)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        AppLogs.setFont(font)
        AppLogs.setStyleSheet("background-color:rgb(23, 60, 76);\n"
"color: rgb(255, 255, 255);")
        self.gridLayout = QtWidgets.QGridLayout(AppLogs)
        self.gridLayout.setObjectName("gridLayout")
        self.text_logs = QtWidgets.QTextBrowser(AppLogs)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(9)
        self.text_logs.setFont(font)
        self.text_logs.setObjectName("text_logs")
        self.gridLayout.addWidget(self.text_logs, 0, 0, 1, 1)

        self.retranslateUi(AppLogs)
        QtCore.QMetaObject.connectSlotsByName(AppLogs)

    def retranslateUi(self, AppLogs):
        _translate = QtCore.QCoreApplication.translate
        AppLogs.setWindowTitle(_translate("AppLogs", "Frame"))
        self.text_logs.setHtml(_translate("AppLogs", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AppLogs = QtWidgets.QFrame()
    ui = Ui_AppLogs()
    ui.setupUi(AppLogs)
    AppLogs.show()
    sys.exit(app.exec())
