from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogManageExpenses(object):
    def setupUi(self, DialogManageExpenses):
        DialogManageExpenses.setObjectName("DialogManageExpenses")
        DialogManageExpenses.resize(424, 389)
        self.layoutWidget = QtWidgets.QWidget(DialogManageExpenses)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 400, 351))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_name = QtWidgets.QLabel(self.layoutWidget)
        self.label_name.setMinimumSize(QtCore.QSize(80, 0))
        self.label_name.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_name.setObjectName("label_name")
        self.horizontalLayout_3.addWidget(self.label_name)
        self.text_name = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_name.sizePolicy().hasHeightForWidth())
        self.text_name.setSizePolicy(sizePolicy)
        self.text_name.setMinimumSize(QtCore.QSize(0, 28))
        self.text_name.setMaximumSize(QtCore.QSize(16777215, 28))
        self.text_name.setObjectName("text_name")
        self.horizontalLayout_3.addWidget(self.text_name)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 7, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_rate = QtWidgets.QLabel(self.layoutWidget)
        self.label_rate.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_rate.setObjectName("label_rate")
        self.horizontalLayout.addWidget(self.label_rate)
        self.text_rate = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_rate.sizePolicy().hasHeightForWidth())
        self.text_rate.setSizePolicy(sizePolicy)
        self.text_rate.setMinimumSize(QtCore.QSize(80, 28))
        self.text_rate.setMaximumSize(QtCore.QSize(80, 28))
        self.text_rate.setObjectName("text_rate")
        self.horizontalLayout.addWidget(self.text_rate)
        spacerItem1 = QtWidgets.QSpacerItem(35, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btn_add_new = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_add_new.setEnabled(False)
        self.btn_add_new.setMinimumSize(QtCore.QSize(0, 27))
        self.btn_add_new.setObjectName("btn_add_new")
        self.horizontalLayout.addWidget(self.btn_add_new)
        self.btn_update = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_update.setEnabled(False)
        self.btn_update.setMinimumSize(QtCore.QSize(0, 27))
        self.btn_update.setObjectName("btn_update")
        self.horizontalLayout.addWidget(self.btn_update)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.text_filter = QtWidgets.QLineEdit(self.layoutWidget)
        self.text_filter.setMinimumSize(QtCore.QSize(0, 22))
        self.text_filter.setMaximumSize(QtCore.QSize(16777215, 22))
        self.text_filter.setObjectName("text_filter")
        self.verticalLayout.addWidget(self.text_filter)
        self.tv_filter_box = QtWidgets.QTableView(self.layoutWidget)
        self.tv_filter_box.setObjectName("tv_filter_box")
        self.verticalLayout.addWidget(self.tv_filter_box)
        spacerItem3 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.btn_delete = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_delete.setEnabled(False)
        self.btn_delete.setMinimumSize(QtCore.QSize(90, 27))
        self.btn_delete.setObjectName("btn_delete")
        self.horizontalLayout_2.addWidget(self.btn_delete)
        spacerItem5 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.btn_close = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_close.setMinimumSize(QtCore.QSize(90, 27))
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_2.addWidget(self.btn_close)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(DialogManageExpenses)
        QtCore.QMetaObject.connectSlotsByName(DialogManageExpenses)
        DialogManageExpenses.setTabOrder(self.text_name, self.text_rate)
        DialogManageExpenses.setTabOrder(self.text_rate, self.btn_add_new)
        DialogManageExpenses.setTabOrder(self.btn_add_new, self.btn_update)
        DialogManageExpenses.setTabOrder(self.btn_update, self.text_filter)
        DialogManageExpenses.setTabOrder(self.text_filter, self.btn_delete)
        DialogManageExpenses.setTabOrder(self.btn_delete, self.btn_close)
        DialogManageExpenses.setTabOrder(self.btn_close, self.tv_filter_box)

    def retranslateUi(self, DialogManageExpenses):
        _translate = QtCore.QCoreApplication.translate
        DialogManageExpenses.setWindowTitle(_translate("DialogManageExpenses", "Manage Expenses"))
        self.label_name.setText(_translate("DialogManageExpenses", "Expense Name"))
        self.label_rate.setText(_translate("DialogManageExpenses", "Rate in INR"))
        self.btn_add_new.setText(_translate("DialogManageExpenses", "Add"))
        self.btn_update.setText(_translate("DialogManageExpenses", "Update"))
        self.btn_delete.setText(_translate("DialogManageExpenses", "Delete"))
        self.btn_close.setText(_translate("DialogManageExpenses", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogManageExpenses = QtWidgets.QWidget()
    ui = Ui_DialogManageExpenses()
    ui.setupUi(DialogManageExpenses)
    DialogManageExpenses.show()
    sys.exit(app.exec())
